version: "3.8"

services:
  backend-flask:
    build: ./backend-flask
    ports:
      - "4567:4567"
    environment:
      BACKEND_URL: "http://localhost:4567"
      FRONTEND_URL: "http://localhost:3000"
    volumes:
      - ./backend-flask:/backend-flask
    command: python3 -m flask run --host=0.0.0.0 --port=4567 --reload
    networks:
      - internal-network

  frontend-react-js:
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
    volumes:
      - ./frontend-react-js:/app
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
    name: cruddur
