version: "3.8"

services:
  backend-flask:
    container_name: backend-flask-container
    build: ./backend-flask
    ports:
      - "4567:4567"
    environment:
      BACKEND_URL: "http://backend-flask:4567"
      FRONTEND_URL: "http://frontend-react-js:3000"
    volumes:
      - ./backend-flask:/backend-flask
    command: python3 -m flask run --host=0.0.0.0 --port=4567 --reload
    networks:
      - internal-network

  frontend-react-js:
    container_name: frontend-react-js-container
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: "http://backend-flask:4567"
    volumes:
      - ./frontend-react-js:/app
    networks:
      - internal-network

  dynamodb-local:
    # Added root user to avoid write permission issues
    user: root
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - internal-network

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal-network

volumes:
  db:
    driver: local

networks:
  internal-network:
    driver: bridge
    name: cruddur
